FROM node:19.4.0
WORKDIR /app

# Set environment variables for API endpoints
ENV NEXT_PUBLIC_API_BASE_URL=http://ZennMo-ZennM-TvhjwDMmd5sI-2146470207.ap-northeast-1.elb.amazonaws.com/api/v1
ENV NEXT_PUBLIC_FRONT_BASE_URL=http://ZennMo-ZennM-TvhjwDMmd5sI-2146470207.ap-northeast-1.elb.amazonaws.com